name: tests

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose build

      - name: Start postgres
        run: docker compose up -d

      - name: Wait for postgres
        run: |
          sleep 15

      - name: Run tests
        run: docker compose exec -T pg ./run_tests.sh
